### ISSUE TITLE
Should I still use LegacyMockInterface

### ISSUE THREAD

**Issue by ruudk** [mockery/mockery#1019]
When I create a mock it returns a mock that implements https://github.com/mockery/mockery/blob/master/library/Mockery/MockInterface.php. 

That interface has 2 methods `allows` and `expects` and extends from https://github.com/mockery/mockery/blob/master/library/Mockery/LegacyMockInterface.php.

This interface is called the legacy interface. Does that mean it's still the way to go? Or will this be removed in V2?

**Comment by davedevelopment** [comment]
It's a strange one, the only reason we have the `LegacyMockInterface` is to support mocking classes that have `allows` and `expects` methods, which clash with the `MockInterface`'s methods of the same name. If a class has `allows` or `expects` methods, then Mockery will return something that implements `LegacyMockInterface`, rather than `MockInterface`. 

As far as my thinking goes, we don't plan on removing this feature.

**Comment by SMillerDev** [comment]
It's almost 6 years later and PHPStorm tells you to stop using the legacy methods nowadays, are they wrong or did something change in the meantime?

**Comment by kdg-cwood** [comment]
@SMillerDev  You might open a new issue about that if you're still wondering. ("PHPStorm says not to use legacymockinterface..."). I am curious too but I don't have phpstorm.

**Comment by SMillerDev** [comment]
I don't see how that is actionable for the Mockery volunteer developers. Jetbrains is the one who should fix that issue. I was just here to check if it became deprecated after all.

**Comment by kdg-cwood** [comment]
@SMillerDev  Doh! Good point, thanks!
