### ISSUE TITLE
mockery/mockery: 1.4.x-dev not found

### ISSUE THREAD

**Issue by prathna124** [mockery/mockery#1334]
### Mockery Version

1.4.x-dev

### PHP Version

PHP 8.0

### Issue Description

I have use composer require exodusanto/administrator package in this package dependency to mockery package and I have use  exodusanto/administrator 8.1.0 that require mockery version 1.4.x-dev that no available in packagiest so got below error:

Problem 1
    - Root composer.json requires exodusanto/administrator 8.1.1 -> satisfiable by exodusanto/administrator[8.1.1].
    - exodusanto/administrator 8.1.1 requires mockery/mockery 1.4.x-dev -> found mockery/mockery[dev-feature/refactor-internal-classes, dev-remove-comments-from-mock-pass, dev-chore/setup-ci-tests-php84, dev-feature/types, dev-mock-internals, dev-chore/add-blackfire, dev-main, dev-refctor/1.7.x/count-validator, dev-issue-1190/address-bc-changes-test-did-not-perform-any-assertions-error, dev-feature/php82/mock-readonly-classes, 0.7.2, ..., 0.9.x-dev, 1.0.0-alpha1, ..., 1.7.x-dev, 2.0.x-dev] but it does not match the constraint.
    
    Guide me How to solve this issue.

**Comment by ghostwriter** [comment]
Hey @prathna124,

Thanks for reporting this issue; 

As you’ve already reported https://github.com/exodusanto/Laravel-Admin/issues/48, I’ve gone ahead and create a pull request to address this issue https://github.com/exodusanto/Laravel-Admin/pull/49

Once it’s merge, you will be able to use `composer update` to update your projects dependencies.

Ps. please close this issue here so we can track the progress in  https://github.com/exodusanto/Laravel-Admin/issues/48
 one place.

**Comment by prathna124** [comment]
@ghostwriter 
After Composer Update We have still faced issues.

**Comment by ghostwriter** [comment]
> After Composer Update We have still faced issues.

We may need to wait for this https://github.com/exodusanto/Laravel-Admin/pull/49 pull request to be merged by the author…

Or update your composer.json to use your own fork of that library.
