### ISSUE TITLE
HHVM supports mocking of final classes and methods

### ISSUE THREAD

**Issue by dwlnetnl** [mockery/mockery#458]
Please support HHVM's __MockClass attribute. "This attribute allows final methods and final classes to be overridden." See https://github.com/facebook/FBMock for an implementation in a mock library and the HHVM source for the implementation in the runtime. (https://github.com/facebook/hhvm/blob/eafd55a09e9f264e6ba6eab1fe3727f045d78c8e/hphp/hhbbc/class-util.h#L59)

**Comment by aik099** [comment]
Can you please create a PR, that adds described support?

**Comment by padraic** [comment]
It sounds a little divergent. If we support this, won't we become complicit in having test suite support diverge across PHP and HHVM? It will work...but only if you are on HHVM? That, I'm not sure is really Mockery's problem. HHVM is intended to be compatible with PHP, and in PHP you cannot mock final classes through extension because they are final.

A more compatible approach would be intercepting the original file dynamically - which is oddly enough possible though I didn't know it while writing Mockery ;). See Humbug's StreamWrapper for example while let me get rid of runkit as a dependency.

**Comment by dwlnetnl** [comment]
I purpose to add the HHVM's attribute only if the code is running on HHVM.

**Comment by robertbasic** [comment]
As this is oddly specific, and not worked on for over 2 years, I'm closing it.

Please reopen this issue with a pull request implementing the feature request if you want it in Mockery.

Thanks!
