### ISSUE TITLE
Mockery exceptions being caught in tested code

### ISSUE THREAD

**Issue by luispabon** [mockery/mockery#613]
As per title. When an expectation fails on a Mockery mock, it throws an exception which is caught by application exception catchers instead of being aggregated at the test case level. It's impossible to know what expectation failed unless you actually go in code to where the exception is being caught and dump the exception for information.

**Comment by luispabon** [comment]
Example here:

git@github.com:luispabon/mockery-exception-issue.git

Run example: `composer install; vendor/bin/phpunit Stuff.php`

**Comment by davedevelopment** [comment]
You'll need to deal with that in your application code somehow, I don't think there's a decent way for Mockery to deal with it.

**Comment by luispabon** [comment]
My application shouldn't really be aware of testing, it's the other way around. 

PHPUnit mocks do it, not sure how. I imagine the mocks don't throw exceptions and instead aggregate violations into a collector?

**Comment by luispabon** [comment]
Looks like phpunit collects and aggregates all exceptions thrown by their assertions on the test case. Would need to plug into this mechanism somehow, which could also be a cleaner way to integrate with PHPUnit than the current one of merely incrementing the assertion count.

**Comment by davedevelopment** [comment]
That's not really within the scope for mockery in my opinion.

**Comment by kathiedart** [comment]
Maybe there could be a way of saying "Actually we're catching exceptions, so throw errors instead"?
Since there are things like "unexpected method call" this sounds like it's closer to an error anyway.

Is there at least an option, or a way to more closely play to PHPUnit optionally so that it will see these...
... or just by moving checks to after the application has run, so that it'll see there are expectations it hasn't notified about and notify you? It seems there's a lot of PHPUnit integration here, so it's probably going to be a PHPUnit scope problem as you said.

**Comment by davedevelopment** [comment]
I can't really see switching to throwing errors as being doable.

> or just by moving checks to after the application has run, so that it'll see there are expectations it hasn't notified about and notify you

Yes, one of the options is to move to using spies in smaller parts of code like this one https://github.com/luispabon/mockery-exception-issue:

``` php
        $dependencyMock = \Mockery::spy(Dependency::class);
        $application = new Application($dependencyMock);
        $application->run();
        $dependencyMock->shouldHaveReceived('bar'); // throws
```

With global level exception handlers, your tests should really be avoiding those if possible. If they can't be avoided, I'd recommend adding a `disable` method to your exception handler so that you can disable when necessary within tests.

**Comment by kathiedart** [comment]
Fair enough, if it's a bad smell it should be able to be avoided. Sounds like a good topic for a blog post!

**Comment by robertbasic** [comment]
Closing, as this is something that should be fixed on application code level - not doing a blanket catch on all types of exceptions.

**Comment by luispabon** [comment]
I'm not sure you guys actually understood what the problem is. Mockery is throwing exceptions when expectations are unmet that bubble up to application level. This shouldn't be happening.

**Comment by robertbasic** [comment]
Reopening the issue as it was misunderstood by us.

**Comment by robertbasic** [comment]
Even if we trigger_error instead of throwing a BadMethodCall exception, PHPUnit will change that to a PHPUnit exception and your `catch(\Exception $e)` blanket statement will catch and silence it.

**Comment by luispabon** [comment]
Right, so the problem is that mockery exceptions are bubbling up past the test suite (phpunit in this case) into the code being tested and interfering with said code.

In the example I posted, a Mockery assertion is unmet, yet still the tests pass because the Mockery exception has been caught by exception handling in the class being tested. This certainly shouldn't be the case, as otherwise I would need to make the class being tested a) aware that's being tested and b) being tested with both phpunit and mockery.

Instead, Mockery should be aggregating the errors someplace else then handing them over to PHPUnit.

**Comment by robertbasic** [comment]
@luispabon but Mockery isn't only to be used with PHPUnit, we support other testing frameworks as well. And at the time when Mockery's PHPUnit integration kicks in, your `try/catch` block has already happened and the code is executed.

For PHP 7, we could potentially change the bad method call exception to a custom error extending `\Error`, but for PHP 5.6, we're pretty much stuck.

Other thing that comes to mind, is to have a configuration setting to trigger errors instead of throwing exceptions and then in your `phpunit.xml` you should set `convertWarningsToExceptions="false"` and finally the error will bubble up to PHPUnit and the test will fail.

Or you could just not catch the general `\Exception` in your code :/

Calling in the higher powers for their 5 pennies @davedevelopment @padraic

**Comment by luispabon** [comment]
I completely get what you're saying, but as you can see, not catching \Exception is not really an option, especially when you're doing functional tests of portions of an app instead of individual units.

I've updated the repo with a counter example using PHPUnit mocks, in this case even though an assert exception is thrown, it won't make it up to application level.

**Comment by robertbasic** [comment]
Another possible solution could be:

Instead of throwing the exception here https://github.com/mockery/mockery/blob/ceb487b82ea332a414eb946522a1cfe7a78572b2/library/Mockery/Mock.php#L817-L819 we added to an internal array of bad method calls, and then actually throw them in `mockery_verify()` method https://github.com/mockery/mockery/blob/ceb487b82ea332a414eb946522a1cfe7a78572b2/library/Mockery/Mock.php#L381

The problem with this, is that the stack trace will then look like something:

```
BadMethodCallException: Method Mockery_0_Dependency::foo() does not exist on this mock object

/home/robert/projects/mockery-exception-issue/vendor/mockery/mockery/library/Mockery/Container.php:297
/home/robert/projects/mockery-exception-issue/vendor/mockery/mockery/library/Mockery/Container.php:282
/home/robert/projects/mockery-exception-issue/vendor/mockery/mockery/library/Mockery.php:142
/home/robert/projects/mockery-exception-issue/vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php:54
/home/robert/projects/mockery-exception-issue/vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php:38
```

instead of the actual

```
BadMethodCallException: Method Mockery_0_Dependency::foo() does not exist on this mock object

/home/robert/projects/mockery-exception-issue/Stuff.php:29
/home/robert/projects/mockery-exception-issue/Stuff.php:56
```

**Comment by robertbasic** [comment]
But there's `$previous` to the rescue:

```
1) Test::doTest
BadMethodCallException: Method Mockery_0_Dependency::foo() does not exist on this mock object

/home/robert/projects/mockery-exception-issue/vendor/mockery/mockery/library/Mockery/Container.php:297
/home/robert/projects/mockery-exception-issue/vendor/mockery/mockery/library/Mockery/Container.php:282
/home/robert/projects/mockery-exception-issue/vendor/mockery/mockery/library/Mockery.php:142
/home/robert/projects/mockery-exception-issue/vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php:54
/home/robert/projects/mockery-exception-issue/vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php:38

Caused by
BadMethodCallException: Method Mockery_0_Dependency::foo() does not exist on this mock object

/home/robert/projects/mockery-exception-issue/Stuff.php:29
/home/robert/projects/mockery-exception-issue/Stuff.php:56
```

**Comment by davedevelopment** [comment]
@luispabon I disagree that it shouldn't be throwing the exceptions, I consider that a feature. PHPUnit would do the same thing if you configured it's mock in the same way as Mockery.

```
   /**
    * @test
    */
   public function doTest()
   {
       $mock = $this->createMock(Dependency::class);
       $mock->expects($this->never())->method('foo');
       $mock->expects($this->any())->method('bar')->willReturn('foo');

       $application = new Application($mock);
       $application->run();
   }
```

However, PHPUnit also counts the failures and shows them at the end. This is something we could do I think, but it's probably a bit more awkward for us as we don't get the luxury of deep integration with PHPUnit.

Also worth noting, Prophecy behaves the same as Mockery, despite the deep PHPUnit integration.

``` php
   /**
    * @test
    */
   public function doTest()
   {
       $dependencyMock = $this->prophesize(Dependency::class);
       $dependencyMock->bar()->willReturn('foo');

       $application = new Application($dependencyMock->reveal());
       $application->run();
   }
```

**Comment by robertbasic** [comment]
I've made an attempt with #736
