### ISSUE TITLE
'Public API' returning `@internal` interfaces?

### ISSUE THREAD

**Issue by gsdevme** [mockery/mockery#723]
Hi,

I've noticed the the method `mock` in `Mockery\Mockery` has a docblock to state its returning ` \Mockery\MockInterface` .. However this interface is flagged as internal? 

If you ever want to build something ontop of Mockery you end up with this uglyness in the IDE.. My understanding of `@internal` is it shouldn't be exposed via the public API.. this would lead me to suggest the `@internal` docblock is wrong on the `MockInterface`? 

I see this change as adding it two months ago by @davedevelopment 
https://github.com/mockery/mockery/commit/f6b38e6c84ec6cf96402a7dd1ffda1fdf4c19056

It could be the 'Public API' is meant to return the concrete class `Mock`? Either way if you let me know which you prefer I can PR it. 

Ref-1 
![screen shot 2017-04-15 at 05 07 53](https://cloud.githubusercontent.com/assets/319498/25060622/83947ab0-2199-11e7-9820-23e52ef4a076.png)

Thanks. Good Library 👍

**Comment by davedevelopment** [comment]
Ugh, that's annoying. 

My intentions with that were to show that the MockInterface isn't really an extension point. I wanted the flexibility to add methods to that interface without breaking BC, so I though I could get away with marking it as `@internal`.  `MockInterface` is definitely what the API returns, so I'll have to revert that and think of some other way of communicating it.

**Comment by gsdevme** [comment]
Hmm, in that case perhaps you want two interfaces? The public API would expose an interface than the internal project would use the adapter pattern to convert it to a private interface. Than all the break changes would be isolated within the adapter and you provide non breaking changes by adapting the interfaces to each other. Then you can slowly deprecate the public interface in a safe way over time.

That might not fit with the project though or might be a chore to even implement.

**Comment by davedevelopment** [comment]
Removing methods isn't the problem, it's adding them that is. When people see an interface, they should feel like they can create a class that implements the interface and use it where the library accepts it, and that interface is stable and won't change in minor version bumps (assuming semver). That is, it's perfectly acceptable for someone to think they can do something like:

``` php
class MyMock implements Mockery\MockInterface {
// bunch of methods
}

Mockery::getContainer()->rememberMock(new MyMock());
```

I can't imagine why they would, but having an interface like `Mockery\MockInterface` available sounds like that's what we are offering. When really, we aren't! We use `MockInterface` internally mostly to allow us to identify a Mock object (as they usually extend some other class). I wanted to be free to *add* methods o `MockInterface`, without breaking peoples apps because they had created their own implementations, so I added the @internal tag, trying to convey "This could change in minor version bumps". 

I think the best thing to do is remove the `@internal` tag and hope for the best.

**Comment by MarcusSchwarz** [comment]
@davedevelopment You could add some text after the annotation, that way PhpStorm ignores it.

```
/**
* @internal Do not use this for foo
*/
```
would be ignored, while

```
/**
* @internal
*/ 
```
triggers the notice in the screenshot above.

For the internal-annotation this is valid: https://www.phpdoc.org/docs/latest/references/phpdoc/tags/internal.html

Tested in PHPStorm 2017.1.1
