### ISSUE TITLE
with(Mockery::on(function doesn't work for multiple args

### ISSUE THREAD

**Issue by Deracination** [mockery/mockery#752]
On PHP 5.6.30, composer --dev mockery/mockery

Using a closure to mock a method call doesn't work as suggested by the documentation with multiple args for the method. It fails as Mockery\Expectation\matchArgs() tests whether the number of args === the number of expected args for the matcher. A single closure means this is always a count() == 1.

This method test with two args fails with a NoMatchingExpectationException
```

class Tester {
    public function TestMe($one,$two) {
        print "$one, $two\n";
    }
}

$mock = Mockery::mock('Tester');

$mock->shouldReceive('TestMe')
    ->once()
    ->with(Mockery::on(function($one,$two){
        print "SEEN $one, $two\n";

        return true;
    }));

$mock->TestMe(1,2);
```

The actual way to with() with multiple args is to have multiple ::on args
```
class Tester {
    public function TestMe($one, $two) {
        print "$one, $two\n";
    }
}

$mock = Mockery::mock('Tester');

$mock->shouldReceive('TestMe')
    ->once()
    ->with(Mockery::on(function($one){
        print "SEEN ONE $one\n";
        return true;
    }),
Mockery::on(function($two){
        print "SEEN TWO $two\n";
        return true;
    }));

$mock->TestMe(1,2);
```

**Comment by robertbasic** [comment]
That's because Mockery::on is meant to be used only on one argument, and
not on any number of them. You need an expect per argument.

On May 28, 2017 3:06 AM, "Chris" <notifications@github.com> wrote:

Trying to use a closure to mock a method call doesn't seem to work when
there are multiple args for the method as Mockery\Expectation\matchArgs()
tests whether the number of args === the number of expected args for the
matcher.

This method test with two args fails with a NoMatchingExpectationException


class Tester {
    public function TestMe($one,$two) {
        print "$one, $two\n";
    }
}

$mock = Mockery::mock('Tester');

$mock->shouldReceive('TestMe')
    ->once()
    ->with(Mockery::on(function($one,$two){
        print "SEEN $one, $two\n";

        return true;
    }));

$mock->TestMe(1,2);

This single arg method passes (no exception)

class Tester {
    public function TestMe($one) {
        print "$one\n";
    }
}

$mock = Mockery::mock('Tester');

$mock->shouldReceive('TestMe')
    ->once()
    ->with(Mockery::on(function($one){
        print "SEEN $one\n";

        return true;
    }));

$mock->TestMe(1);

I'm working around this using andReturnUsing, but it's really messy as all
the test case assertions end up in the andReturnUsing closure.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mockery/mockery/issues/752>, or mute the thread

**Comment by robertbasic** [comment]
@Deracination wait, where does the documentation say that the `on` matcher can match multiple arguments?

**Comment by Deracination** [comment]
It doesn't. I just read the documentation as suggesting that. I now realise that it's per-argument and actually works!
