### ISSUE TITLE
Is this support PHP 7 ?

### ISSUE THREAD

**Issue by phpspider** [mockery/mockery#764]
I am using php 7.0.10 with phpunit 6.1 and getting the following error 

Class "Mockery\Adapter\Phpunit\TestListener" does not implement the PHPUnit\Framework\TestListener interface

**Comment by padraic** [comment]
@phpspider There were some changes to PHPUnit 6 which make the use of a Listener for integration difficult. You will need to check the documentation, and use one of the alternate methods which are compatible with 6.x.

**Comment by jasonetwork** [comment]
I've been having the exact same issues. I've read and reread the documentation many times over and am yet to get Mockery working with the latest version of PHPUnit. Can somebody shed some light on what "alternate methods" are compatible with 6.x.

**Comment by davedevelopment** [comment]
The alternative method is to extend the [MockeryTestCase](https://github.com/mockery/mockery/blob/master/library/Mockery/Adapter/Phpunit/MockeryTestCase.php) or `use` the [MockeryPHPUnitIntegration](https://github.com/mockery/mockery/blob/master/library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php).

The test listener is only compatible with PHPUnit 5 at the minute, there was a PR (#695) that made it compatible with PHPUnit 6, at the expense of PHPUnit 5, which I requested be changed to support both. Given the amount of time that has passed, I'm more open to dropping PHPUnit 5 support as we aim for Mockery 1.0.

The test listener doesn't function as it should, so I recommend using the base class or the trait now. This was due to changes in PHPUnit beyond our control, see #376 and sebastianbergmann/phpunit#1440.

**Comment by jasonetwork** [comment]
When using the MockeryPHPUnitIntegration trait, any "failures" are displayed as errors when running PHPUnit tests. For example:

```
There was 1 error:

1) Tests\OAuth2\AccessTokenTest::generate_TokenRegenerated_OnDuplicateToken
Mockery\Exception\InvalidCountException: Method tokenExists() from Mockery_3_Core_OAuth2_AccessTokens should be called
 exactly 2 times but called 1 times.

/var/www/vendor/mockery/mockery/library/Mockery/CountValidator/Exact.php:37
/var/www/vendor/mockery/mockery/library/Mockery/Expectation.php:298
/var/www/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:120
/var/www/vendor/mockery/mockery/library/Mockery/Container.php:297
/var/www/vendor/mockery/mockery/library/Mockery/Container.php:282
/var/www/vendor/mockery/mockery/library/Mockery.php:152
/var/www/vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php:24

```

Is there something that I am missing which is causing this strange action?

**Comment by robertbasic** [comment]
This past week [Mockery 1 was tagged](https://github.com/mockery/mockery/releases/tag/1.0) and it indeed does support PHP 7.

For integrating Mockery with PHPUnit, please take a look at the [documentation for the integration](https://github.com/mockery/mockery/blob/1bac8c362b12f522fdd1f1fa3556284c91affa38/docs/reference/phpunit_integration.rst).

I'm going to close this issue now, but please feel free to open a new issue with a detailed explanation of what's going on if you still have problems with using Mockery with PHPUnit.
