### ISSUE TITLE
Pull up `expects()` method to the `MockInterface`

### ISSUE THREAD

**Issue by JavierCane** [mockery/mockery#793]
Hi!

I've always used the following method in order to set expectations:
```php
$repository = Mockery::mock(SomeRepository::class);
$repository->shouldReceive('search')->once()->andReturn($xxx);
```

I'm using `"mockery/mockery": "^1.0@dev"` for the first time in order to be able to upgrade to `"phpunit/phpunit": "^6.3"`. I've seen in [the Method Call Expectations ReadMe section](https://github.com/mockery/mockery/blob/master/README.md#method-call-expectations-) that you recommend the usage of the `expects()` method. It seems a little bit clearer for me setting the expectations this way, so I've bet for it 🙂:
```php
$repository = Mockery::mock(SomeRepository::class);
$repository->expects()->search()->once()->andReturn($xxx);
```

The problem comes when I try to type hint this `$repository` instance. If I type hint it to a `\Mockery\Mock` instance, I receive the following error while running the tests:

>TypeError: Argument 1 passed to someMethod() must be an instance of Mockery\Mock, instance of Mockery_0_All_My_Whole_Namespace_SomeRepository given

So in order to make it run without type errors, I have to type hint to the `\Mockery\MockInterface` interface. However, the `expect()` method signature is not defined in this interface, so calling to this method while type hinting to the interface ends up believing in something more related to Duck Typing and runtime faith, rather than the actual type system.

**What do you think about pulling up the `expects()` method signature to the `\Mockery\MockInterface` interface in order to be able to properly use type hint?**

**Comment by davedevelopment** [comment]
I don't quite understand the bit in the middle, but I agree with your conclusion, ideally `expects` and `allows` should be added to `MockInterface`.

The reason they were not added, was to try and keep some backwards compatibility. If someone using Mockery already had `expects` or `allows` methods in the class or interface they were mocking, Mockery would not add those methods to a Mock in order to keep BC, so they couldn't be added to the interface. 

I'm happy to break this for 1.0 (#791), the signatures will need adding to the interface and the magic removing from the generator.

**Comment by JavierCane** [comment]
Perfect then @davedevelopment, waiting for the 1.0 release :)

**Comment by davedevelopment** [comment]
#794 should be accepted or rejected before I fix this.

**Comment by JavierCane** [comment]
Tested after upgrading to `"mockery/mockery": "^1.0"` and working perfectly.

Thanks for your work!!!
