### ISSUE TITLE
not working properly with return types

### ISSUE THREAD

**Issue by bogdan-dubyk** [mockery/mockery#881]
I'm using mockery  1.1 witn PHP 7.1 and  have such code:
Factory with method : 
```
public function getScrapperByUrl($type):AppScrapperInterface
{
    $this->validate($type);
    switch ($type) {
        case self::ITUNES:
            return app(ITunesScrapper::class);
            break;
        case self::PLAYSTORE:
            return app(PlayStoreScrapper::class);
            break;
        default:
            throw new AppScraperException("Can't scrap info");
    }
}
```

and I'm mocking ITunesScrapper:
```
$m = m::mock(ITunesScrapper::class);
    $scrapedInfo = [
        'name' => "comico",
        'downloads' => ""
    ];
    $m->shouldReceive('getOfferAnchor')->with(m::any())->andReturn($scrapedInfo['name']);
    $m->shouldReceive('getOfferDownloads')->with(m::any())->andReturn($scrapedInfo['downloads']);
    App::instance(ITunesScrapper::class, $m);
```

and getting error 

> TypeError: Return value of Scrappers\ScrapperFactory::getScrapperByUrl() must be an instance of Scrappers\AppScrapperInterface, instance of Mockery_2__Scrappers_Itunes_ITunesScrapper returned.

**Comment by adridev** [comment]
I faced the same problem today with version 0.9.4. It's working properly after update to 1.1.0. 

PHP version 7.2

**Comment by bogdan-dubyk** [comment]
@adridev  yeah, it's known issue on version 0.9, but I have 1.1*

**Comment by robertbasic** [comment]
@bogdan-dubyk that's probably because Mockery can't know that `ITunesScrapper` implements the `AppScrapperInterface` interface.

In your tests, you should either create a mock of the `AppScrapperInterface` interface, or tell Mockery that when mocking the `ITunesScrapper` class, it should implement `AppScrapperInterface` interface as well.

Please refer to the documentation on how to do that: http://docs.mockery.io/en/latest/reference/creating_test_doubles.html#classes-abstracts-interfaces

**Comment by robertbasic** [comment]
Closing as there was no feedback for quite some time. If this is still an issue for you, please open new a detailed issue, thanks!
